# Generated by Django 3.2.23 on 2023-12-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomapp', '0006_auto_20231204_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
