# Generated by Django 3.2.23 on 2023-12-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomapp', '0008_alter_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
